### ISSUE TITLE
Solving multi objective TSP

### ISSUE THREAD

**Issue by shvkb** [rgaveiga/mosa#2]
While solving a multi objective TSP Problem, a error is showing like this
line 491, in evolve
    if ftmp[k]<fcurr[k]:

What is the reason of this?

**Comment by shvkb** [comment]
Yes, thank you very much. After deleting the archive.json file, it works. But in case of multi-objective, the solutions coming out to be very far from the pareto-front (solved using exact method). How can I improve the solution quality Prof.?

**Comment by shvkb** [comment]
Yes sir, I have raised the temperature and increased the number of failed attempts. Still it only can provide 10-15 datapoints at the end. And there is a gap between exact and this solution.

**Comment by rgaveiga** [comment]
Ok, can you share the function defining the problem or the script, as well as the expected value? Because this is what can be done. If you run the algorithm a couple of times considering the same checkpoint/archive and it stops improving, it is trapped for some reason.

**Comment by shvkb** [comment]
`def fobj(solutions):
coords1=Cities[0]

    coords2=Cities[solutions["Cities"][0]]
    total_dist=sqrt((coords2[0]-coords1[0])**2+(coords2[1]-coords1[1])**2)
    for i in range(1,len(solutions['Cities'])):
        coords1=Cities[solutions["Cities"][i-1]]
        coords2=Cities[solutions["Cities"][i]]        
        total_dist+=sqrt((coords2[0]-coords1[0])**2+(coords2[1]-coords1[1])**2) 
coords1=Cities[solutions["Cities"][-1]]
    coords2=Cities[0]
    total_dist+=sqrt((coords2[0]-coords1[0])**2+(coords2[1]-coords1[1])**2)
wij_dij=sum(Citylist[:,2])*dij[0,solutions["Cities"][0]]
    wij=sum(Citylist[:,2])
    for i in range(1,len(solutions["Cities"])):
        wij-=Citylist[i,2]
        wij_dij+=wij*dij[solutions["Cities"][i-1],solutions["Cities"][i]]`

As you can see, the fobj function tries to minimize the dual objective - total distance (can be total time also) and total weighted distance. Can you comment on this Prof?

**Comment by rgaveiga** [comment]
I don't understand very well the meaning of this weighted distance, maybe because I know only the simplest TSP problem. In principle, if the problem is implemented correctly, you should expect the final result to approximate the Pareto set. The algorithm is quite sensitive to the parameter choice, as the initial temperature and the number of failed attempts to insert a solution in the archive. What I did for testing purposes before uploading the Jupyter notebooks was some calibration. You can also run the algorithm a few times starting from the same archive to be sure the solutions are not improved anymore. Or do what I did in the alloy_optmization problem, perform different runs and them merge the results. If even so the solutions are not improved, it means that, for some reason, the algorithm is trapped before reaching the Pareto set.

**Comment by shvkb** [comment]
Sir tried with the multi-archive settings as you mentioned in the Alloy examples, still only 4-5 solutions are coming at the end. Also note that temperature is decreasing only one time. The snippet is as below -

Keys in the population/solution dictionaries:
    ['Cities']:
        Number of elements in the solution: 15
        Discrete sample space
        Number of elements in the population: 15
        Elements cannot be repeated in the solution: True
        Selection weight of this key: 1.000000
        Weight of 'swap' trial move: 1.000000
        Solution sorted after trial move: False
------
Initializing with a random solution from scratch...
Done!
------
TEMPERATURE: 10000.000000
    Number of accepted moves: 1913.
    Fraction of accepted moves: 0.956500.
    Number of archive updates: 21.
    Fraction of archive updates in accepted moves: 0.010978.
------
TEMPERATURE: 9000.000000
    Insertion in the archive consecutively rejected 1000 times!
    Quiting at iteration 875...
------

--- THE END ---
   Elapsed time: 5.178272 s
===
Solutions:
1) {'Cities': [15, 8, 11, 14, 6, 3, 2, 13, 9, 4, 7, 10, 1, 12, 5]}
2) {'Cities': [6, 9, 12, 10, 5, 4, 13, 11, 8, 3, 7, 1, 2, 15, 14]}
3) {'Cities': [6, 13, 12, 9, 5, 4, 11, 8, 10, 14, 7, 1, 2, 15, 3]}
4) {'Cities': [8, 6, 9, 7, 12, 13, 10, 4, 1, 11, 5, 15, 3, 2, 14]}
5) {'Cities': [13, 4, 11, 8, 5, 12, 6, 9, 1, 7, 10, 15, 2, 3, 14]}
Values:
1) [90.0, 10143.5278907364]
2) [72.0, 9647.33550658874]
3) [75.0, 10162.798532483741]
4) [72.0, 9428.603420860973]
5) [76.0, 10015.767642728493]

**Comment by rgaveiga** [comment]
When you plot the two objective functions, did you get the same curve?
You said you have an analytical solution (I must confess I did not know it). The shape of the analytical curve and its position, how different/far is it when compared with the simulated one?
As a last try, I would increase the archive rejection threshold and, after the hot run, I would run a cold run, since for the extremely hot run you have less than 1% of the accepted moves inserted in the archive (non-dominated solutions).

**Comment by shvkb** [comment]
I think the algorithm is trapped for some reason. The shape of the simulated one is far from the exact one (done for a small size of problem). One relevant question, is this MOSA can be applied to multi-objective VRP? If not what are the things that need to be changed?

**Comment by rgaveiga** [comment]
Being trapped is always possible dependind on the choice of optimization parameters (such as the temperature, temperature decay factor, number of temperatures, number of iterations per temperature, etc) or intrinsic flaws of the MOSA algorithm I am not aware of, I observed that in tests of the single objective TSP where I got trapped in local minima. However, since I don't know how the exact solution of this multi-objective TSP that you proposed is obtained, I cannot go further. What you can do is to try to use differente algorithms, such as NSGA ou NSPSO. You can find these algorithms implemented in very good optmization frameworks, such as PyMOO (https://pymoo.org/algorithms/list.html#nb-algorithms-list) and PyGMO (https://esa.github.io/pygmo2/overview.html), which I used before and I think are pretty good. If you try any of them and get better results, please let me know.
